# Generated by Django 2.2.7 on 2019-11-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test_model1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Test1',
                'verbose_name_plural': 'TEST1',
            },
        ),
    ]
